version: '3'
services:
  postgres:
    image: kartoza/postgis:9.5-2.2
    environment:
      - ALLOW_IP_RANGE="172.18.0.0/16"

  qgis-build-and-test:
    build:
      context: .
      dockerfile: build-Dockerfile
    tty: true
    image: qgis/qgis3-run:${DOCKER_TAG}
    volumes:
      - ${TRAVIS_BUILD_DIR}:/root/QGIS
      - $HOME/.ccache:/root/.ccache  # if changed, also change env var
    links:
      - postgres
    environment:
      - DOCKER_TAG=${DOCKER_TAG}
      - CCACHE_DIR=/root/.ccache
      - CTEST_BUILD_DIR=/root/QGIS
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE}
      - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
      - TRAVIS_CONFIG=${TRAVIS_CONFIG}
